### ISSUE TITLE
Write logic to call ALISS search API for a given postcode

### ISSUE THREAD

**Issue by digitalWestie** [aliss/aliss.js#1]
Use v4, see http://docs.aliss.org/ for details

- [x] search with postcode
- [x] category filter
- [x] query filter
- [x] location_type
- [x] radius
- [ ] page size (low priority)

**Comment by Mike-Heneghan** [comment]
Although it's possible to search by postcode I need to handle errors for bad requests and sort the input I'll get some more of the basic functionality working initially and come back to it.

**Comment by Mike-Heneghan** [comment]
Category filter currently populates all the subcategories as well as the main ones. I need to review the way I'm doing it currently.

**Comment by Mike-Heneghan** [comment]
Need to figure out a better way of handling the categories. At the moment the method is too fragile. Need to improve so that all dropdowns are created programmatically and will continue being generated regardless of hierarchy levels.

**Comment by Mike-Heneghan** [comment]
@digitalWestie we can discuss tomorrow but not sure if we want a user input for radius and page size?
