### ISSUE TITLE
Add pagination UI

### ISSUE THREAD

**Issue by digitalWestie** [aliss/aliss.js#18]

**Comment by Mike-Heneghan** [comment]
Added pagination through params by adding a ```page: 1``` to the ```parametersObject```. Added a hidden message which is shown when users try to go back from the first page.

**Comment by Mike-Heneghan** [comment]
As a work around to display a message to user when they select ```next page``` from the final page. Added a comparison between ```page_size``` and the number of results from the service list. If there are fewer results than requested, on click of ```next page``` the warning message text appears. This won't work if the total number of pages is evenly divisible by the page_size.

**Comment by Mike-Heneghan** [comment]
Basic pagination added although ```next page```from the page of results won't work for edge cases.

**Comment by digitalWestie** [comment]
Re the work-around, isn't next_page `null` when you're on the final page? In which case you don't need to do any division etc?

**Comment by Mike-Heneghan** [comment]
I had been using the ```next``` and ```previous``` keys with the links, but that was adding complications as I wanted to search with params to be consistent. So I added ```page: 1``` to the ```request```  ```parametersObject```. The page is then incremented and decremented with next and previous respectively. The previous checks for page > 1 for the warning to appear. The next on the other hand doesn't have an awareness of a max number of pages. Hence as a workaround, I added a check that if there are fewer services than requested in the ```parametersObject``` it won't try to go to another page and will display the warning. 

```
var handlePageChange = function (event) {
 
  if (event.target.value === "next"){ 
    
    if (window.request.parametersObject["page_size"] > $(".aliss-service-card-div").length) {
         $('#aliss-no-next-message').show();
        }
    
    else {
      window.request.parametersObject["page"] += 1;
      apiRequest(renderServiceList);
      renderPagination();
    }
    }
  
  if (event.target.value === "previous") {
    
    if (window.request.parametersObject["page"] > 1){
      window.request.parametersObject["page"] -= 1;
      apiRequest(renderServiceList);
      renderPagination();
    }
    else {
      $('#aliss-no-previous-message').show();
    }
  }
}
```
I can have a think about it and find a better way of handling it though.

**Comment by Mike-Heneghan** [comment]
Added a hidden <p> at the top of the service list which holds the response.next of the return form the api. Now works for all cases. Although adding a hidden element to save something seems like bad practice 😅

```
var handlePageChange = function (event) {
 
  if (event.target.value === "next"){ 
    
    if ($('#aliss-next-page-link').val() === "") {
         $('#aliss-no-next-message').show();
        }
    
    else {
      window.request.parametersObject["page"] += 1;
      apiRequest(renderServiceList);
      renderPagination();
    }
    }
  
  if (event.target.value === "previous") {
    
    if (window.request.parametersObject["page"] > 1){
      window.request.parametersObject["page"] -= 1;
      apiRequest(renderServiceList);
      renderPagination();
    }
    else {
      $('#aliss-no-previous-message').show();
    }
  }
}
```
