### ISSUE TITLE
Write initialise function

### ISSUE THREAD

**Issue by digitalWestie** [aliss/aliss.js#3]
`var aliss = ALISS.init('#target-element')` - should populate target element with ALISS search form and results

**Comment by Mike-Heneghan** [comment]
Slightly different from the above, but the way I've done it presumes that the user has a div with the id of ```"aliss-target"``` and they call ```var aliss = new ALISS(); aliss.init()```. They have the option of then calling the optional methods to change defaults such as page size and whether elements will be hidden.
