### ISSUE TITLE
User should be able to supply options to control category behaviour

### ISSUE THREAD

**Issue by digitalWestie** [aliss/aliss.js#4]
e.g. 

```
var options = {
  category: 'money-advice'
  show-category-select: false 
};

aliss('#target-element', options);
```

nb - split behaviour and visual options, e.g. turn on / off category select

**Comment by Mike-Heneghan** [comment]
The category can be predetermined and when postcode is searched it will be automatically selected although the subcategory does not render.

**Comment by Mike-Heneghan** [comment]
If the custom category chosen by user is a sub-category the category options do not render properly yet.

**Comment by Mike-Heneghan** [comment]
Hey @digitalWestie I'm not sure we'll be able to have the categories drop-down and sub-category autocomplete when the user adds a custom parameter like:

```
var aliss = new ALISS();
        aliss.init();
        aliss.setCategory("money-advice");
```

Because the category objects don't know their parent by themself? 
So money-advice doesn't know it's parent is 'money' so we couldn't set the top level with 'money'. 

Although when a sub-category is set as above the service list is fine so we could have a condition that the users hides the categories if they enter a sub-category?

**Comment by digitalWestie** [comment]
@Mike-Heneghan yep, I see what you mean. If they pre-define a category then don't bother showing the category select controls.

Also, for this first version can we define options in the form of an object (see the example in the original issue comment).

**Comment by Mike-Heneghan** [comment]
At the moment I have it that the user would customise behaviour with meythods on the ALISS object so the below:
```  
  $(document).ready(function(){
        var aliss = new ALISS();
        aliss.init();
        aliss.setPageSize(3);
        aliss.setCategory("money");
        aliss.setKeyword("energy");
        // aliss.hideCategory();
        // aliss.hideKeywordSearch();
    });
```
Would result in:
![image](https://user-images.githubusercontent.com/36415632/43902451-0a4adefa-9be2-11e8-981c-e471bf2f2d8d.png)

Although I can definitely reconfigure the above with the options object as per the issue comment if you'd prefer.

**Comment by digitalWestie** [comment]
Yeah please if you could. The functions are certainly handy though, so please don't remove them!

**Comment by Mike-Heneghan** [comment]
```  $(document).ready(function(){
        
        var options = {
          "category": "money",
          "show_category_select": true,
          "q": "energy",
          "show_keyword_search": true,
          "page_size": 5,
        }
        
        var aliss = new ALISS();
        aliss.init($('#aliss-target'), options);
    });
```

**Comment by Mike-Heneghan** [comment]
Added another aliss.init method which only takes the target div so that basic implementations don't have to create an empty options object. 

In ALISS.js:
```
// For basic implementation of the ALISS.js app
ALISS.prototype.init = function (target) {
//   Creates new request object for aliss instance
  window.request = new Request();
//   Now that request object is made generate form in the supplied div
  generateForm(target);
}
```
In index.html
```
var aliss = new ALISS();
        aliss.init($('#aliss-target'));
```
